version: "{build}"

# AppVeyor jobs por OS
image:
  - Visual Studio 2022    # Windows
  - macos-monterey        # macOS
  - Ubuntu2004            # Linux

test: off

branches:
  only:
    - main
    - release/*

skip_tags: true
clone_depth: 1
shallow_clone: true

environment:
  NODE_VERSION: 20
  CSC_IDENTITY_AUTO_DISCOVERY: false

install:
  # Node.js
  - ps: |
      if ($isWindows) {
        Install-Product node $env:NODE_VERSION
      } else {
        nvm install $env:NODE_VERSION
        nvm use $env:NODE_VERSION
      }
  - node -v
  - npm -v

  # Web (React + Vite)
  - cd web
  - npm install --legacy-peer-deps --no-fund --no-audit
  - npm run build
  - cd ..

  # Desktop (Electron)
  - cd desktop
  - npm install --legacy-peer-deps --no-fund --no-audit
  - cd ..

build_script:
  # Copiar frontend compilado → Electron
  - if exist desktop\app rmdir /s /q desktop\app || true
  - mkdir desktop\app || true
  - robocopy web\dist desktop\app /E || cp -r web/dist/* desktop/app || true

  # Build multi-OS con electron-builder
  - cd desktop
  - npm run dist
  - cd ..

artifacts:
  - path: desktop/dist/*.exe
    name: Windows-Installer
  - path: desktop/dist/*.dmg
    name: macOS-Installer
  - path: desktop/dist/*.AppImage
    name: Linux-Installer

# Deploy: GitHub Release
deploy:
  provider: GitHub
  release: v$(APPVEYOR_BUILD_VERSION)
  description: "QuantumCore auto-build (Windows, macOS, Linux)"
  auth_token:
    secure: %GITHUB_TOKEN%
  draft: false
  prerelease: false
  on:
    branch: main
