version: '{build}'
image: Ubuntu2204   # <- JAMMY: glibc reciente
build: off
test: off

environment:
  CI: true

install:
  - sh: |
      set -e
      curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
      sudo apt-get install -y nodejs jq
      if [ -f package.json ]; then
        npm ci || npm install
      fi

build_script:
  - sh: |
      set -e
      if [ -f package.json ]; then
        if npm run | grep -q " build"; then
          npm run build
        else
          echo "[info] no 'build' script; skipping"
        fi
      fi

after_build:
  - sh: |
      if [ -d dist ]; then
        zip -r artifact.zip dist
      elif [ -d build ]; then
        zip -r artifact.zip build
      else
        zip -r artifact.zip .
      fi

artifacts:
  - path: artifact.zip
    name: quantumcore-build

cache:
  - node_modules -> package-lock.json
