version: "{build}"
image: "Visual Studio 2022"
build: off
test: off

install:
  - ps: |
      $ErrorActionPreference = "Continue"
      node -v
      if (Test-Path "package.json") { cmd /c "npm install --no-fund --no-audit 2>&1" }

build_script:
  - ps: |
      $ErrorActionPreference = "Stop"

      # 1) Detectar carpeta a empaquetar
      $src = "dist"
      if (-not (Test-Path $src)) {
        if (Test-Path "build") { $src = "build" } else { $src = "." }
      }

      # 2) Nombres de salida
      $ver = $env:APPVEYOR_BUILD_VERSION
      $out1 = "QuantumCore-v$ver-windows.zip"
      $out2 = "QuantumCore-latest-windows.zip"

      # 3) Empaquetar
      if ($src -eq ".") {
        $temp = "qc_pack"
        if (Test-Path $temp) { Remove-Item -Recurse -Force $temp }
        New-Item -ItemType Directory -Force -Path $temp | Out-Null
        robocopy . $temp /E /XD node_modules .git /XF appveyor.yml > $null
        $code = $LASTEXITCODE
        if ($code -gt 3) { Write-Warning "robocopy code $code" }
        Compress-Archive -Path "$temp\*" -DestinationPath $out1 -Force
      } else {
        Compress-Archive -Path (Join-Path $src "*") -DestinationPath $out1 -Force
      }

      Copy-Item $out1 $out2 -Force

      # 4) Checksums
      $lines = @()
      foreach ($f in @($out1, $out2)) {
        if (Test-Path $f) {
          $h = (Get-FileHash $f -Algorithm SHA256).Hash
          $lines += "$h  $f"
        }
      }
      Set-Content "SHA256SUMS-windows.txt" ($lines -join "`r`n") -Encoding ascii

artifacts:
  - path: QuantumCore-v$(APPVEYOR_BUILD_VERSION)-windows.zip
  - path: QuantumCore-latest-windows.zip
  - path: SHA256SUMS-windows.txt
