version: "{build}"
image: Visual Studio 2022
test: off

branches:
  only:
    - main
    - release/*

skip_tags: true
clone_depth: 1
shallow_clone: true

environment:
  NODE_VERSION: 20
  CSC_IDENTITY_AUTO_DISCOVERY: false

install:
  # Node.js
  - ps: Install-Product node $env:NODE_VERSION
  - node -v
  - npm -v

  # Web (React + Vite)
  - cd web
  - npm install --legacy-peer-deps --no-fund --no-audit
  - npm run build
  - cd ..

  # Desktop (Electron)
  - cd desktop
  - npm install --legacy-peer-deps --no-fund --no-audit
  - cd ..

build_script:
  # Copiar frontend compilado → Electron
  - if exist desktop\app rmdir /s /q desktop\app
  - mkdir desktop\app
  - robocopy web\dist desktop\app /E

  # Build Windows
  - cd desktop
  - npm run dist
  - cd ..

artifacts:
  - path: desktop\dist\*.exe
    name: Windows-Installer
  - path: desktop\dist\*.dmg
    name: macOS-Installer
  - path: desktop\dist\*.AppImage
    name: Linux-Installer

deploy:
  provider: GitHub
  release: v$(APPVEYOR_BUILD_VERSION)
  description: "QuantumCore auto-build"
  auth_token:
    secure: %GITHUB_TOKEN%
  artifact: Windows-Installer,macOS-Installer,Linux-Installer
  draft: false
  prerelease: false
  on:
    branch: main
