image: Visual Studio 2022

environment:
  NODE_VERSION: 20

install:
  - ps: |
      Set-StrictMode -Version Latest
      $ErrorActionPreference = "Stop"
      Install-Product node $env:NODE_VERSION
      cd web
      npm ci
      npm run build
      cd ..
      cd desktop
      npm ci
      cd ..

build_script:
  - ps: |
      if (Test-Path 'desktop\\app') { Remove-Item -Recurse -Force 'desktop\\app' }
      New-Item -ItemType Directory -Force -Path 'desktop\\app' | Out-Null
      robocopy web\\dist desktop\\app /E | Out-Host
      Copy-Item desktop\\package.json desktop\\package.json.bak -Force
      Push-Location desktop
      cmd /c "npm run pack:win"
      $exe = Get-ChildItem release\\*.exe | Select-Object -First 1
      Copy-Item $exe.FullName "..\\QuantumCore-Setup-latest.exe" -Force
      Pop-Location

artifacts:
  - path: QuantumCore-Setup-latest.exe
    name: QuantumCore-Setup
