version: "{build}"

image: Visual Studio 2022

environment:
  nodejs_version: "18"
  ELECTRON_CACHE: C:\Users\appveyor\AppData\Local\electron\Cache
  ELECTRON_BUILDER_CACHE: C:\Users\appveyor\AppData\Local\electron-builder\Cache

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --legacy-peer-deps

build_script:
  - npm run dist

artifacts:
  - path: dist\*
    name: installers

deploy:
  release: v$(APPVEYOR_BUILD_VERSION)
  description: "QuantumEdge Enterprise auto-build"
  provider: GitHub
  auth_token:
    secure: %GITHUB_TOKEN%
  artifact: installers
  draft: false
  prerelease: false
  on:
    branch: main
