version: '{build}'
image: Ubuntu
build: off
test: off

environment:
  CI: true

init:
  - sh: ls -la

install:
  - sh: |
      set -e
      # Instala Node 20
      curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
      sudo apt-get install -y nodejs jq
      # Dependencias del proyecto (si hay package.json)
      if [ -f package.json ]; then
        npm ci || npm install
      fi
      # (Opcional) si tienes Hardhat, compila contratos
      if [ -f hardhat.config.js ]; then
        npx --yes hardhat compile || echo "[info] hardhat compile skipped"
      fi

build_script:
  - sh: |
      set -e
      if [ -f package.json ]; then
        # Compila si existe script "build"
        if npm run | grep -q " build"; then
          npm run build
        else
          echo "[info] No 'build' script in package.json; skipping build."
        fi
      else
        echo "[warn] No package.json; nothing to build."
      fi

after_build:
  - sh: |
      # Empaqueta artefacto
      if [ -d dist ]; then
        zip -r artifact.zip dist
      elif [ -d build ]; then
        zip -r artifact.zip build
      else
        zip -r artifact.zip .
      fi

artifacts:
  - path: artifact.zip
    name: quantumcore-build

cache:
  - node_modules -> package-lock.json
